import type { Metadata } from "next";
import "../globals.css";
import Navigation from "./Components/navigation";
import { cookies } from "next/headers";
import Connect from "../auth/connect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PainelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const connect = cookieStore.get('e3b0c44');

  return (
    <>
      { connect && <Connect /> }
      <Navigation />
      <main className="h-[92vh] flex justify-center p-4">
        {children}
      </main>
    </>
  );

}
