import type { Metadata } from "next";
import "../globals.css";
import Navigation from "./Components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PainelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="mb-5">
        <Navigation />
      </header>
      <main className="h-screen flex justify-center">
        {children}
      </main>
    </>
  );
}
