import type { Metadata } from "next";
import "../globals.css";
import Navigation from "./Components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PainelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      <main className="h-[92vh] flex justify-center p-4">
        {children}
      </main>
    </>
  );
}
